# Generated by Django 5.1 on 2024-08-29 04:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PetData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("descirption", models.CharField(max_length=1024)),
                (
                    "creation_date_date",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="date created"
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[("MAC", "MAC"), ("HOST", "HOST"), ("MDNS", "mDNS")],
                        default="MAC",
                        max_length=4,
                    ),
                ),
                (
                    "mac_address",
                    models.CharField(
                        blank=True,
                        help_text="Only required if identifier_type is 'MAC'.",
                        max_length=17,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_mac_address",
                                message="Enter a valid MAC address.",
                                regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
