# Generated by Django 5.1 on 2024-08-21 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petdata",
            name="identifier_type",
            field=models.CharField(
                choices=[
                    ("IP", "IP"),
                    ("MAC", "MAC"),
                    ("DNS", "DNS"),
                    ("MDNS", "mDNS"),
                ],
                default="IP",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="petdata",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="Only required if identifier_type is 'IP'.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="petdata",
            name="mac_address",
            field=models.CharField(
                blank=True,
                help_text="Only required if identifier_type is 'MAC'.",
                max_length=17,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mac_address",
                        message="Enter a valid MAC address.",
                        regex="^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$",
                    )
                ],
            ),
        ),
    ]
