# Generated by Django 5.1 on 2024-11-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_pets", "0002_rename_descirption_petdata_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="petdata",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("PC", "PC"),
                    ("LAPTOP", "Laptop"),
                    ("PHONE", "Phone"),
                    ("IOT", "IoT"),
                    ("SERVER", "Server"),
                    ("ROUTER", "Router"),
                    ("MEDIA", "Media"),
                    ("GAMES", "Games"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=8,
            ),
        ),
    ]
