# Generated by Django 5.1.4 on 2025-01-11 21:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manage_pets", "0003_petdata_device_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petdata",
            name="mac_address",
        ),
        migrations.AddField(
            model_name="petdata",
            name="identifier_value",
            field=models.CharField(default="cat", max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="petdata",
            name="creation_date_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date created"
            ),
        ),
        migrations.AlterField(
            model_name="petdata",
            name="identifier_type",
            field=models.CharField(
                choices=[("MAC", "MAC"), ("HOST", "HOST"), ("IP", "IP")],
                default="MAC",
                max_length=4,
            ),
        ),
    ]
